### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by fugu13** [cassproject/CASS#1]
A number of open source licensed files have been copied into the project, but without following the licenses completely. For example, a number of files from forge are included, and you can find the license for forge here: https://github.com/digitalbazaar/forge/blob/master/LICENSE

Many of those files lack any licensing mention at all, such as: https://github.com/cassproject/CASS/blob/c7ad25089e93f10b77122a9df5456f0ec94766a9/src/webapp/cass.manager/forge/cipher.js

Others mention the licensing situation and link to the forge licensing file, but only reference it for themselves: https://github.com/cassproject/CASS/blob/master/src/webapp/cass.manager/forge/forge/ssh.js

However, the terms of the forge licenses aren't covered by just doing the latter, and are even less covered by doing the former. Since the CASS project is attempting to go Apache 2.0 for licensing, only the BSD license is viable. The BSD license requires that, in source code, the source code retain the license and the specific as-is clause. Files of either sort above do not.

Luckily this issue is fairly mild; it just gets more and more painful to fix the longer it goes unfixed.

One other licensing issue worth calling out is the inclusion of the LGPL'd json2xml code ( https://github.com/cassproject/CASS/blob/master/src/webapp/cass.example/js/vendor/json2xml.js ). That code is not compatible with the project's Apache 2.0 license ( http://www.apache.org/legal/resolved.html#category-x ).

There may be other licensing issues throughout, these are just ones that jumped out at me as I was looking through parts of the code. (Additionally, the structure of the code is going to make it difficult to update it as libraries change).

**Comment by Lomilar** [comment]
Thanks for the notice. I will continue to do a pass and update licenses.

Opened issue with Forge regarding this: https://github.com/digitalbazaar/forge/issues/382

Included license.txt file in forge directory
Reduced use of libraries down to prime.worker.js and forge.min.js (this doesn't solve the problem, of course).

Replacing json2xml with another library that is Apache 2 compatible. Update incoming.

**Comment by Lomilar** [comment]
Going to be moving towards native browser crypto and using Forge as a backup (and as non-included source) if possible.

**Comment by Lomilar** [comment]
Forge is dual-licensed under BSD and GPL. We chose the BSD license. Included licenses to update soon.
