### ISSUE TITLE
Bug: invites are not copied to the clipboard when using CASS in Ubuntu.

### ISSUE THREAD

**Issue by devlinjunker** [cassproject/CASS#10]

**Comment by devlinjunker** [comment]
@eddavies Any specific browser that this occured on? I'll try to see if there is a workaround for it. 

May want to improve this copy similar to how other apps deal with it (auto copy to clipboard, but also provide a non-editable text box to copy the invitation from in case auto copy doesn't work)

**Comment by eddavies** [comment]
This occurred on firefox. I'm going to check firefox on windows 10 quickly
as well.

**Comment by eddavies** [comment]
Yeah it doesn't copy while using firefox specifically.

**Comment by Lomilar** [comment]
It looks like firefox doesn't support JS based clipboard operations. Explaining this in an alert and asking them to copy the text would be an okay workaround.

http://stackoverflow.com/questions/21696052/copy-to-clipboard-with-javascript-in-firefox

**Comment by Lomilar** [comment]
Completed.
