### ISSUE TITLE
Bug: when using the assertion processor - the graphic is never created (stuck on processing assertions) when selecting certain competencies 

### ISSUE THREAD

**Issue by devlinjunker** [cassproject/CASS#12]
specifically one imported from ASN

**Comment by devlinjunker** [comment]
found by @eddavies

**Comment by whistlinjoe** [comment]
Hey Eddie,

Could you please give me an example of a competency that this happens with?

Thanks,
Tom B.

**Comment by eddavies** [comment]
Seems to be working now. Attempted with more ASN frameworks as well, worked fine.
