### ISSUE TITLE
Deletions need to cause websocket change notifications.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#129]
Should be shortId(), not long ID.

**Comment by woodkri** [comment]
A frameworkDeleted message is coming through on the CE test site.

**Comment by Lomilar** [comment]
That is if the user themselves deletes something. If a different user deletes something, that needs to come through as well. Needed for cassproject/cass-vlrc.

EC 2.6.6 and 2.7.0 have this, as does CaSS 1.0.6, 1.0.7
