### ISSUE TITLE
Login screen needs create account option.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#134]

**Comment by Lomilar** [comment]
Should also be able to log in as a guest (no identity)

**Comment by eddavies** [comment]
This is working (sometimes takes a little while for the profile to be created though). Do we care if users can create multiple accounts on a single email address?

**Comment by Lomilar** [comment]
No. Though it keeps creeping in, account management is not intended to be done by CaSS.

**Comment by eddavies** [comment]
Okay, we can close this issue for now. The function is working at the moment.
