### ISSUE TITLE
CTDL-ASN Import of a CTDL-ASN export (non CE) doesn't work very well.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#137]
Repro: Export CTDL-ASN framework from a personal CaSS instance
Import into CTITest
Doesn't seem to import.

**Comment by woodkri** [comment]
I tried exporting from a personal instance and back into the same instance, got a message that the object can't be found. I then tried the same thing but defined ceasnExportUriPrefix and graph before exporting, and that time the import worked fine. An export of a case framework also worked fine. Seems like maybe a versioning issue? Neither of the successful export/imports had versions in the id. Just removing the version before importing doesn't solve the problem though.

**Comment by Lomilar** [comment]
I expect that the id needs to be shortened (version removed) when creating the framework and the alignments. We may be missing one of those.

**Comment by Lomilar** [comment]
Works well now.
