### ISSUE TITLE
Case import works on sandbox but not on dev or local servers

### ISSUE THREAD

**Issue by woodkri** [cassproject/CASS#142]

**Comment by woodkri** [comment]
Ready for testing after next deployment to dev

**Comment by Lomilar** [comment]
Deployment scheduled for today.

**Comment by Lomilar** [comment]
Deployment complete.

**Comment by eddavies** [comment]
After testing this on dev, I can see the import among the list of frameworks after importing from CASE, however it took over 4 minutes, and it didn't direct me to the framework, just the search parameter's "opensalt" :

![long long import](https://user-images.githubusercontent.com/23706850/57392637-2f96c380-7176-11e9-9c94-e708b9fc4f45.PNG)

**Comment by eddavies** [comment]
Additionally I went into the framework explorer after importing a framework from case and got this:

![after importing from case](https://user-images.githubusercontent.com/23706850/57392924-e3984e80-7176-11e9-9806-b1b784c389a8.PNG)

**Comment by woodkri** [comment]
The search for the URL endpoint is by design for CASE since you can import several frameworks at the same time. From your screenshot above I realized the search wasn't working right, but it should be now.

Smaller frameworks will take less time to import, but several of the CASE frameworks are pretty large so they will take a while to complete.

I'm not sure what's going on with the framework explorer though. It displays Norm Webb's framework (also CASE but 15 competencies) and PCG Compendium for Mathematics (746 competencies) but not Massachusetts Curriculum Framework for Mathematics (1577) so perhaps it's a size issue.

**Comment by Lomilar** [comment]
Framework Viewer part of this conversation has had a separate issue created for it.

**Comment by eddavies** [comment]
Okay then we are probably fine closing this if the framework viewer issue is tracked elsewhere.
