### ISSUE TITLE
CTDL-ASN Export sometimes outputs children in the wrong order.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#145]
in https://dev.cassproject.org/api/ceasn/8c754d3012205e7c360bd07c89cc683c

https://sandbox.credentialengineregistry.org/resources/ce-39df838a-8fdc-4a9b-991a-9ecd33975fc3
is supposed to be at the top of the list of
https://sandbox.credentialengineregistry.org/resources/ce-3e296dc1-4975-4d3d-9e85-e6d030aa63cf

but it is not. CE ASN Export should sort the hasChild list by the cardinality of each competency in the parent CaSS Framework.

**Comment by Lomilar** [comment]
Can you double check? Should be live (on test).

**Comment by cwd-mparsons** [comment]
I republished the framework and the order is now correct/retained
credfinder.siuccwd.com/Competencyframework/ce-4e06cda5-057d-440a-b162-3fabe8f7e16d
![image](https://user-images.githubusercontent.com/26332112/56700126-31fd1600-66be-11e9-94d3-122f7806674a.png)
