### ISSUE TITLE
dev.cassproject back button usage

### ISSUE THREAD

**Issue by eddavies** [cassproject/CASS#147]
Currently, using the browser back button does not send the user to the previous page they were on, instead it sends them to the url they were at before. Users will run into this a lot since there are a lot of tools to checkout.

**Comment by eddavies** [comment]
Just figured out this doesn't occur with every screen. Will find a list of situations where this does happen.

**Comment by eddavies** [comment]
It seems to just blow over past the home page. So if you were in the cass framework editor then went to the home screen then to the concept editor, then clicked back, it would send you to the cass framework editor screen.

**Comment by Lomilar** [comment]
For some further understanding: We hook the browser back button to handle transitions between pages. This functionality is something that was not well understood during the development of cass-editor, so it could probably use another entire pass.
