### ISSUE TITLE
New Debugging step

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#153]
When installing, it is possible that the shell file get pulled in the wrong encoding format.

After [this StackExchange answer](https://unix.stackexchange.com/a/237464) I converted the shell script, and it ran fine.

Not really an issue, but may be useful for documentation purposes

**Comment by Lomilar** [comment]
f277a08bbf4d5fdcc4196ec2e097d8752ec16e3b fixes the issue.

To be documented in troubleshooting.
