### ISSUE TITLE
xAPI not triggering assertions

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#160]
When pushing xAPI statements to CaSS that align with an alignment object, no assertion is being generated for the user.

Was this functionality removed from CaSS 1.2.25?

**Comment by Lomilar** [comment]
Nope, though we do now require the user to exist in the system before we generate assertions for them, and for their Person object to either be public or shared with the xAPI adapter.

http://devs.cassproject.org/index.html?doc=1MZP-gvkbTSgea7wJBUylDlGaAeBNuhH-smAcGOuxTx0#h.6dhx7uhuvzmc

Does the user you are trying to generate assertions for exist, have a public Person object, and have their email or identifier matching the xAPI statement?

**Comment by FlorianTolk** [comment]
I am unsure if my profile is public and/or shared with the xAPI adapter. 
When I look at the UI, the private box is not checked however.
![image](https://user-images.githubusercontent.com/33456535/67701101-b5593600-f985-11e9-8095-23897dcb0951.png)

Is there another UI I can use, or endpoint I can query for this information?

**Comment by FlorianTolk** [comment]
After trying to replicate the problem on a fresh install everything seems to run smoothly now

**Comment by FlorianTolk** [comment]
On a different not, unlike 0.4, 1.2 does not send the "asserted" statements any longer. Does "turning on" the adapter in adapter.xapi.json file reactivate that function?

**Comment by Lomilar** [comment]
It does not. See #161 for more detail.

**Comment by FlorianTolk** [comment]
Does Cass 1.2.15 handle this differently?
The dockerhub image 
(at 1.2.15) doesn't seem to generate assertions while the uncontainerized latest version (1.2.25) does generate assertions when a compliant statement is pushed to its xAPI endpoint
