### ISSUE TITLE
Cass share assertions

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#161]
In 2018 Cass had the ability to send xAPI statements when a new assertion is generated. Is this function still available, or a similar "simple forwarding" function still available?

**Comment by Lomilar** [comment]
That code was part of the specific implementation we did for the TLA. It would not be difficult to reproduce.

There was a TLA xAPI profile that included 'asserts' -- can you point me at that?

**Comment by FlorianTolk** [comment]
We are currently working on releasing a Master Object Model Profile for the TLA that includes verbs for Competency Management, including "asserted." But it hasn't been approved for release.

As for adding functionality to CaSS, you can certainly add this as part of Eduworks internal business goals, but we do not currently have a contractual vehicle by which we can direct that or more importantly, by which you could be compensated for it.
