### ISSUE TITLE
Cass 1.2.29 Crashes with large frameworks

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#164]
When trying to pull up the BOLC common core framework (a framework with 652 items) in the CaSS Competency Editor, it loads for a few minutes, and then displays a framework with 2 empty competencies labeled "New Competency."

I get this error when using the publicly hosted CaSS instance on [dev.cassproject.org](https://dev.cassproject.org) on a Firefox Browser.

**Comment by woodkri** [comment]
This appears to be a data issue for this particular framework. Almost all of the competencies have either been deleted but not removed from the framework object, or encrypted.

CaSS can handle frameworks of that size; see "Science - Georgia Standards of Excellence" for an example with 765 competencies.

**Comment by FlorianTolk** [comment]
Thanks, closing this issue then

**Comment by Lomilar** [comment]
As a follow up, yes, BOLC has issues. I will try to find somewhere else it exists and reimport it on dev. Standby.

**Comment by Lomilar** [comment]
https://cassproject.github.io/cass-editor/?frameworkId=https://dev.cassproject.org/api/data/schema.cassproject.org.0.4.Framework/e708d172-04f9-4b92-bb2a-4c16b161e7b4

**Comment by FlorianTolk** [comment]
Thanks!
