### ISSUE TITLE
Having Issues issues importing into Cass 1.2.25

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#165]
I am trying to pull some frameworks from [https://cassproject.github.io](https://cassproject.github.io) into an instance of Cass 1.2.25.

As this instance is only listed as supporting CTDL-ASN formatted frameworks I tried pulling a few frameworks formatted as Credential Engine ASL (CSV) (see attached image 1)
![image](https://user-images.githubusercontent.com/33456535/74742790-3c7c3380-522d-11ea-874b-02966fc2c2f8.png)

However, when uploading to my local version, I always get the same error:
![image](https://user-images.githubusercontent.com/33456535/74742856-5e75b600-522d-11ea-9728-0d24a36749ae.png)

What am I doing wrong?

**Comment by Lomilar** [comment]
One thing is that you're in the concept editor, not the framework editor.

Not sure if that was the intent.
