### ISSUE TITLE
Editor paths in 1.3 deployment

### ISSUE THREAD

**Issue by woodkri** [cassproject/CASS#187]
If you want to serve 1.3 CaSS out of a folder that isn't ROOT, the editor iframe will not load because the paths are wrong. For example, there's a deployment where we have a cass folder within tomcat's webapps folder and ProxyPass and ProxyPassReverse are not set. If you go to https://<site>/cass/cass-editor, the iframe tries to get https://<site>/cass-editor/css/<chunk> which fails because there's no /cass/ in the URL.

**Comment by Lomilar** [comment]
That is correct. The editor iframe should be using relative paths, but I'm not sure if this is possible in vue. Transfer to cass-editor?

**Comment by woodkri** [comment]
We can move it, I just put it in CaSS since it's deployment-related. It looks like the path '/cass-editor/' is hardcoded in the vue config for non-gitlab deployments but they allow relative paths with '' or './'. I'm not sure how changing that might interact with the rest of the CaSS deployment. It would change the path of the github deployment at the very least.

**Comment by woodkri** [comment]
Editor paths are now relative and will be in the next CaSS release (0.5.5).
