### ISSUE TITLE
Import named graphs of objects

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#23]
Be able to import named graphs of objects as a collection.

**Comment by Lomilar** [comment]
Please retest based on changes we made recently. Testing on dev.cassproject.org works.

**Comment by devlinjunker** [comment]
Uploaded Connecting Credentials jsonld by posting and was able to retrieve from https://dev.cassproject.org/api/custom/asn?id=8eb2d64dff5b2a84c5da255d9d18de5b. A couple of comments though:

We don't have the internal CASS IDs of any of the competencies that are created but still reference the connectingcredentials url ID. Could/should we consider building a map from internal to external ID and storing this in skyrepo as an encrypted object with the ASN adapter key as the owner?

As you mentioned, finding objects by ID takes a while... Searching for all of the competencies in the framework to return them in ASN, or just displaying them in CASS manager take at least a minute to load all 90 credentials. Could we set a flag somewhere (on the object? locally?) to not try resolving the url of competencies (or competencies in a framework).

When we import the ConnectingCredentialsLevels.jsonld, we are still assigning them IDs. We will probably want to change this to be similar to the Framework import, and also assign ownership to the imports.

**Comment by Lomilar** [comment]
We discussed having a flag in the CASS library that, for objects that aren't likely to be on a CASS repository, does a 'find' (on the nearest repository) before a 'get' (targeting the @id). This is a decent first step. I'm reluctant to put additional variables in the data that state "this doesn't resolve", but that may be the best course of action.

As for internal indexing, we should test this at scale by registering a bunch of ASN frameworks in dev and seeing where the slowdown is.

**Comment by Lomilar** [comment]
Put in predictive find (which can be turned off) on 83acfb3dbc5a293c271dfd1ea53b926f48c7d984.

Should probably augment precache and multiget to do this on the serverside as well.

**Comment by Lomilar** [comment]
Precache/Multiget now fetch registered objects. Tested fairly thoroughly.
