### ISSUE TITLE
CaSS Configurations cause UI to crash.

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#235]
I am using CaSS version 1.5.13 from cassproject/cass:node-1.5.13 and when I create a configuration, it breaks the configuration table.

This can be reproduced on the dev server as well: [https://dev.cassproject.org/#/configuration](https://dev.cassproject.org/#/configuration). 

I think it is a problem that shows up on creation, as that is the only time that there is an actual error popping up in the terminal (it is missing a variable called "cfo"), but otherwise I am just getting 200 code responses in any network history, despite the UI getting stuck on the loading page.

Note: if you do not have any configurations in your CaSS image, the UI does load up as expected, with the option to create a configuration, and it only crashing on a refresh after you created and saved your first one.

**Comment by Lomilar** [comment]
This is resolved in node-1.5.14

**Comment by FlorianTolk** [comment]
Can confirm, new version fixes everything. Thanks!
