### ISSUE TITLE
xAPI Adaptor defaults a passing score as failed if the score is less than 70%

### ISSUE THREAD

**Issue by brendon-stephens** [cassproject/CASS#293]
The CASS xAPI adaptor will fail an assertion for an xAPI statement containing the following result object.

```
...
  "result": {
    "score": {
      "raw": 6.66667,
      "min": 0,
      "max": 10,
      "scaled": 0.666667
    },
    "completion": true,
    "success": true,
    "duration": "PT18S"
  }
...
```

The result is an assertion which states the following: `Noisy Client claimed Brendon could not demonstrate [Nutritional Knowledge ](https://cass.example.app/#)because they completed "Nutrition and Hydration Quiz" quiz with a passing 67%.`

Looking at [the adaptor code](https://github.com/cassproject/CASS/blob/master/src/main/server/adapter/xapi/xapi.js#L119-L138), it appears that there are various conditions to set as a pass/fail

```
    if (s.result.score != null) {
        var scaled = s.result.score.scaled;
        if (scaled > 0.7)
            negative = false;
        else
            negative = true;
```

https://github.com/cassproject/CASS/blob/master/src/main/server/adapter/xapi/xapi.js#L119-L138

The code should be updated to check for `response` and `success` properties first, before using the `score` property to determine the pass/fail status. 

I am happy to create a pull request if you agree with the above synopsis.

**Comment by Lomilar** [comment]
Concur, the order should be success first, then score. a PR would be appreciated.
