### ISSUE TITLE
Ubuntu 17.10 doesn't have Tomcat7 in the package manager, can't install CASS.

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#43]
After Downloading CASS and starting the server on my machine I try to access `http://localhost:8080/cass/cass.example/profile.html`

However, before I even sign in, I get this error `TypeError: me.usernameSalt is undefined`

Closing this message takes me to the login page, where I try to create an account, only to get `Remote Identity not configured.` to pop up twice. and then just an empty profile, where all of the buttons prompt me to try and log in again.

I am using Ubuntu 17.10, and therefore had to update tomcat to tomcat8 if that makes any difference. 

How do I fix this?

**Comment by Lomilar** [comment]
>I am using Ubuntu 17.10, and therefore had to update tomcat to tomcat8 if that makes any difference.

It may. CASS requires the tomcat8 directory be chowned to the tomcat user. Try that?

Me: Check to see if the installer chowns the tomcat directory just once or repeatedly.

**Comment by FlorianTolk** [comment]
It chowns tomcat8 and tomcat8/backup to tomcat8 and then chowns  tomcat and tomcat/backup to tomcat

**Comment by Lomilar** [comment]
Got it, yeah. Is the tomcat8 directory chowned on the machine you're working on? You mentioned having to upgrade tomcat. That could have resulted in permissions changes.

**Comment by FlorianTolk** [comment]
It should have been. I just edited the cassInstall.sh file to use tomcat8 and chown it.

**Comment by Lomilar** [comment]
What flavor of linux? Redhat distros use /usr/share/tomcat vs /var/lib/tomcat8 -- want to make sure you haven't found a Redhat flavored distro that uses /tomcat8.

**Comment by FlorianTolk** [comment]
No I'm using Ubuntu 17.10, that's why I had to upgrade to tomcat8

**Comment by Lomilar** [comment]
Got it! That makes sense now. Ubuntu 17.10 doesn't have tomcat7 in the package manager.

TODO: Migration script from tomcat7 to tomcat8.
Affects: 0.3, master

**Comment by Lomilar** [comment]
Note: Tomcat8 on Ubuntu 16.04 has some bugs that may preclude its use regarding dynamic classes. Test thoroughly.

**Comment by Lomilar** [comment]
Current build that uses Tomcat 8 is based on Ubuntu 18.04
