### ISSUE TITLE
Explore credential assertions.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/CASS#46]
* Should we advance assertions to include credential assertions? 
* What credential assertion models exist out there? 
* Which should we use?

**Comment by rrobson** [comment]
Do you mean assertions of credentials that are not evidence of competencies?  If so, that is an interesting idea. Open Badges can be used to make assertions. They do not reference competencies, and they don't have a decay function, and they don't have the ability to make negative assertions, but I think they can do what CaSS assertions do with those exceptions.  Overall, I do believe it would be useful to assert the possession of a credential, but I am not sure we want to use OBI ... to me it seems overly complex and there are IP issues in the IMS license.

**Comment by Lomilar** [comment]
@rrobson Per the OBI spec, the open badge Assertion can only target a BadgeClass, similar to how we can only target a Competency in our implementation of Assertion.

Both can reference credentials as evidence, but they should be referencing credential awards, not abstract credentials.

I understand that one interpretation of a badge is as a digital credential, but I am not sure if there's equivalency in both directions there. @ottonomy -- Do you know?

**Comment by Lomilar** [comment]
http://schema.cassproject.org/0.4/index.html#Assertion

Closing, as this is on its way.
