### ISSUE TITLE
Competencies exported from CASS are using ceasn:exactMatch, but should be ceasn:exactAlignment

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/CASS#53]
An example competency is as follows;
"ceasn:exactMatch": [
        "http://credentialengineregistry.org/resources/ce-F374CB30-520A-43CD-A002-ADA6C208787A"
      ],

The ceasn doesn't have an exactMatch property, this should (probably) be exactAlignment.

**Comment by Lomilar** [comment]
Not able to repro this. Can you give me a URL where this happens?

This may have been fixed as part of previous fixes.

**Comment by cwd-mparsons** [comment]
The framework is: Advanced Manufacturing Technician Associate in Applied Science Degree Program
https://cass.credentialengine.org/api/ceasn/schema.cassproject.org.0.3.Framework/11d19ca9-2e0c-43fc-8e41-3d99556e6607/1519329083889

**Comment by Lomilar** [comment]
Ah, this is an artifact of the import process, not of the conversion. It'll be fixed along with cassproject/cass-editor#117.

**Comment by Lomilar** [comment]
Done as part of cassproject/cass-editor#117.
