### ISSUE TITLE
Competencies: Selecting an existing skill from the suggested list results in kick out of edit.

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/CASS#55]
Steps

- Created a new framework
- Specified to create a new competency
- As I started to type, the system listed (type ahead/autocomplete) existing competencies
- I clicked on one of the items in the list
- I got kicked out of the edit view
- The competency was saved with the item selected, but I lost other data that had been entered.

**Comment by eddavies** [comment]
Moved this to cass-editor issue list.
