### ISSUE TITLE
Concept: deleted a concept but still appears in list on the left

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/CASS#56]
In production, created the concept scheme: CER Education Levels
I added a concept of High School.
- added another concept, which defaults to New Concept
- I did not save, and clicked cancel
- The New Concept still shows on the left - that is there appears to be an auto-save. 
   - should an auto-save be done?
- I edited the latter New Concept, and then clicked on Delete. 
- The system prompted to confirm. 
- **I did, but the New Concept item still shows on the left**
- I clicked the return arrow next to the concept scheme name, then immediately clicked on the concept scheme
- The item was actually deleted

**Comment by eddavies** [comment]
Moved this to cass-editor issue list.
