### ISSUE TITLE
Competency: Selecting a concept term added to the wrong section

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/CASS#57]
Steps:
- added a new competency
- Under Skill Embodied, clicked on Create or select
- Created a new concept scheme, and added one concept: Skill One
- Saved, and then clicked on the Add button
- was returned to the competency, but the selected concept was **added to Concept Term, NOT Skill Embodied.** 

Tried a similar test to check for a pattern:
- Under complexity level, clicked on Create or select
- used the same scheme, created skill two, saved and added
- the system did properly add Skill two under Complexity level

**Comment by eddavies** [comment]
fixed in https://github.com/cassproject/cass-editor/issues/143
