### ISSUE TITLE
Export of Concept keywords as language map is incorrect

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/CASS#58]
Language maps may not be used, but just in case, noticed that in production the format of ceasn:conceptKeyword is incorrect in an export:

![image](https://user-images.githubusercontent.com/26332112/37689810-51086a88-2c75-11e8-9a59-2192397c4206.png)

Instead it should be:
![image](https://user-images.githubusercontent.com/26332112/37689944-02dc2024-2c76-11e8-8754-a2adb9bdeec8.png)

**Comment by eddavies** [comment]
Moved this to cass-editor issue list.
