### ISSUE TITLE
alert does not work in nodejs environment

### ISSUE THREAD

**Issue by aecostas** [cassproject/CASS#66]
I am trying to create a user, following the instructions in http://devs.cassproject.org/index.html?doc=1fd37JgWViMlHlRIi4AnTRiC3XJY8gY7Nn1xHMcapbYo and I got this error. 

Apart from the identification problem, a new problem showed up: use of `alert`. In nodejs it is not available, so it breaks the execution

```
undefined:1386
            alert("Remote Identity not configured.");
            ^

ReferenceError: alert is not defined
    at EcRemoteIdentityManager.prototype.startLogin (eval at <anonymous> (/home/aestevez/devel/cass-client/node_modules/cassproject/index.js:57:44), <anonymous>:1386:13)
    at Object.<anonymous> (/home/aestevez/devel/cass-client/competency.js:8:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
```

**Comment by Lomilar** [comment]
Ah, I thought those were all gone. Thanks for catching that.

You can create a polyfill for alert, redirecting it to console.log to bypass this until eduworks/ec#14 is deployed.

```js
alert = console.log;
```

**Comment by Lomilar** [comment]
I suspect I do. My guess is the manager couldn't ask the server for salts (either missing that invocation or it didn't complete for some reason).

```js
m = new EcRemoteIdentityManager();
m.server = "https://dev.cassproject.org/api/"; //Sets the identity server endpoint

//This retrieves username and password salts from the server. 
//-- This would cause the error you saw, if this didn't complete.
m.configureFromServer(console.log,console.log); 

//This takes the username and login and hashes them client side 
//(we never send usernames or passwords over the wire, even via https)
m.startLogin("test","test");

m.fetch(console.log,console.log) //This actually tries to get the data. If no user account exists yet, it'll fail, and you'll need to create one and commit.
```

**Comment by Lomilar** [comment]
Another possibility is that the server endpoint may not be correct. The /api/ part is important.

**Comment by Lomilar** [comment]
Another possibility that came up in a separate conversation:

configureFromServer is an async call. So, `console.log,console.log` are the success and failure callbacks, both saying "print whatever to the console" -- If I were creating workflows:

```js
m.configureFromServer(
  function(success){
    m.startLogin("test","test");
    m.fetch(console.log,console.log);
  }
,console.log); 
```

**Comment by aecostas** [comment]
It works now. It was an issue with my local CASS installation. It works fine with the sandbox. Thanks!
