### ISSUE TITLE
Error saving competency

### ISSUE THREAD

**Issue by aecostas** [cassproject/CASS#69]
I have developed a small function to create and save a competency, but it gives and error, not catched by the error callback. I am using cassproject 0.3.3. Doing something analogous for `Framework` works fine

The code:
```
function createCompetency(server, ppk, name) {
        // [...]
	let c = new EcCompetency();
	c.generateId(name);
	c.addOwner(ppk.toPk());
	c.name = name;

	c.save(() =>
		{
			console.warn('competency saved correctly');
		},
		() =>
		{
			console.warn('error saving competency');
		})

[...]
}
```

Error:
```
/home/aestevez/devel/cass-client/node_modules/xhr2/lib/xhr2.js:206
          throw new NetworkError("Unsupported protocol " + this._url.protocol);
          ^
Error: 

```

**Comment by Lomilar** [comment]
No problem at all, there's no rules or anything about having code questions here, I just presumed it would be faster to get things done in a proper chat app.
