### ISSUE TITLE
Bug: when logging out of the profile manager and logging back in as a different user, the previous account's contacts are copied and added to the new user's list of contacts.

### ISSUE THREAD

**Issue by devlinjunker** [cassproject/CASS#7]

**Comment by devlinjunker** [comment]
Clearing contacts on logout now, needs testing once fix pushed

**Comment by eddavies** [comment]
working as intended

**Comment by eddavies** [comment]
Found two issues concerning this. When inviting someone to be a contact, the newly invited contact is not added to the original users contact list. Additionally the newly invited copies the invitee's contact list (is that intended?).

**Comment by eddavies** [comment]
![duplicate](https://cloud.githubusercontent.com/assets/23706850/20847106/6f614fcc-b881-11e6-909b-1dd855b60e1f.PNG)

Managed to duplicate a contact somehow, trying to recreate.

**Comment by Lomilar** [comment]
Any update on recreating this @eddavies? Would like to close this.
