### ISSUE TITLE
Bug: when creating a new assertion - when clicking on the competency drop down, a black box appears making it impossible to choose a competency.

### ISSUE THREAD

**Issue by devlinjunker** [cassproject/CASS#8]

**Comment by devlinjunker** [comment]
Couldn't reproduce. Can you show me a screenshot? and what OS/Browser/any other specs?

**Comment by eddavies** [comment]
Attached is a screenshot.

**Comment by devlinjunker** [comment]
@eddavies can't see it if you attached it to the email, you'll probably need to login to github

**Comment by eddavies** [comment]
Did you not get it from the email I just you? I can also send it to you via
slack or skype if that's easier. Also reattached it to this email.

**Comment by devlinjunker** [comment]
After talking with @eddavies, it sounds like this was a weird combination of missing fonts on his computer and an import that went awry to create weird competencies and framework names in the database. Closing this because I don't think it is likely to happen again
