### ISSUE TITLE
Docker container reports tomcat not started, when it is started.

### ISSUE THREAD

**Issue by JonathanStoye** [cassproject/CASS#83]
Seems like the docker image is broken. When run it complains it cannot start the tomcat.

I just wanted to mention that as I tried spinning up an instance.

**Comment by Lomilar** [comment]
This is an odd catch 22. The docker image we're using for Ubuntu 16.04 doesn't like keeping track of Tomcat. We now have an alternative in a distributed deployment (if that helps). Will further investigate using a tomcat base image for the docker build.

**Comment by Lomilar** [comment]
New types of docker images exist now. See them here: https://cloud.docker.com/repository/docker/cassproject/cass/tags

The Alpine build doesn't have this issue, for instance.
