### ISSUE TITLE
Document AWS Requirements for ADL TLA Cluster

### ISSUE THREAD

**Issue by kchavas** [cassproject/CASS#84]
Email to me and I will pass on to Brent.

**Comment by Lomilar** [comment]
Minimum requirements are documented here:
http://devs.cassproject.org/index.html?doc=1I5sVZFeOQxr2xvflCmusWuINKeuI9YlkTTXXXFBiQ04

For the TLA demonstraton, we used a t2.2xlarge.
Gooru has a lot more data, so would like at least 30GB of SSD space, though that's a swag.

**Comment by Lomilar** [comment]
Would prefer an Ubuntu instance. If a t3 is used, not sure if Ubuntu is supported.
