### ISSUE TITLE
Case - CFDocuments Endpoint gives error message

### ISSUE THREAD

**Issue by woodkri** [cassproject/CASS#86]
![cfdocuments](https://user-images.githubusercontent.com/33300923/46971454-fdaefa00-d089-11e8-81d7-0878b776efbd.PNG)

/CFDocuments/{sourcedId} does work, but /CFDocuments/ with no id listed gives an error message instead of displaying data on all documents.

**Comment by Lomilar** [comment]
Not yet deployed to dev.

**Comment by woodkri** [comment]
I'm now getting the 404 error for /CFDocuments:

![cfdocuments 404](https://user-images.githubusercontent.com/33300923/50008780-37658980-ff83-11e8-86fa-16d06360a52e.PNG)
