### ISSUE TITLE
Case - CFItems TypeError

### ISSUE THREAD

**Issue by woodkri** [cassproject/CASS#87]
/CFItems/{sourcedId} gives this error message:

![cfitems](https://user-images.githubusercontent.com/33300923/46972053-a0b44380-d08b-11e8-9c1b-38d58a318f5c.PNG)

This is what the CFItems array looks like from the CFPackages endpoint:

![cfitems list - last one in screenshot](https://user-images.githubusercontent.com/33300923/46972099-bfb2d580-d08b-11e8-9aa0-62284b9c2f43.PNG)

**Comment by Lomilar** [comment]
Not yet deployed to dev.

**Comment by woodkri** [comment]
This works for me now.
