### ISSUE TITLE
Case - CFAssociations TypeError

### ISSUE THREAD

**Issue by woodkri** [cassproject/CASS#89]
/CFAssociations/{sourcedId} gives this TypeError message:

![cfassociations](https://user-images.githubusercontent.com/33300923/46973474-52a13f00-d08f-11e8-9648-27550462501c.PNG)

Screenshot of CFAssociations array from CFPackages endpoint:

![cfassociations list](https://user-images.githubusercontent.com/33300923/46973549-93995380-d08f-11e8-9210-992548d14a3a.PNG)

**Comment by woodkri** [comment]
I get the same error message when I try to replace "CFAssociations" with "CFItemAssociations" in the URL.

**Comment by Lomilar** [comment]
Not yet deployed to Dev.

**Comment by woodkri** [comment]
CFAssociations and CFItemAssociations are now working for me.
